export const ADD_GROUP = "ADD_GROUP";

export const LOADING_GROUPS = "LOADING_GROUPS";
export const LOADED_GROUPS = "LOADED_GROUPS";
export const FAILED_LOADING_GROUPS = "FAILED_LOADING_GROUPS";

export const LOADING_GROUP_EVENTS = "LOADING_GROUP_EVENTS";
export const LOADED_GROUP_EVENTS = "LOADED_GROUP_EVENTS";

export const CREATED_GROUP = "CREATED_GROUP";
export const ERROR_CREATING_GROUP = "ERROR_CREATING_GROUP";

export const CREATED_EVENT = "CREATED_EVENT";
export const DELETED_EVENT = "DELETED_EVENT";