export const ADD_GROUP = "ADD_GROUP";

export const LOADING_GROUPS = "LOADING_GROUPS";
export const LOADED_GROUPS = "LOADED_GROUPS";
export const FAILED_LOADING_GROUPS = "FAILED_LOADING_GROUPS";

export const LOADING_GROUP_EVENTS = "LOADING_GROUP_EVENTS";
export const LOADED_GROUP_EVENTS = "LOADED_GROUP_EVENTS";